# Numpy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

In [1]:
import numpy as np

## Arrays

In [2]:
# Define array
a = np.array([1,2,3])

# Some basic properties
print("Array a: ", a)
print("\nShape of array a: ", a.shape)
print("\nData type of array a: ", a.dtype)

Array a:  [1 2 3]

Shape of array a:  (3,)

Data type of array a:  int32


In [3]:
# Define matrix
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.int64)

# Some basic properties
print("Matrix b: \n", b)
print("\nShape of matrix b: ", b.shape)
print("\nData type of matrix b: ", b.dtype)

Matrix b: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape of matrix b:  (3, 3)

Data type of matrix b:  int64


In [4]:
# Multidim arrays - tensor
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]], dtype=np.float64)

# Some basic properties
print("Tensor c: \n", c)
print("\nShape of tensor c: ", c.shape)
print("\nData type of tensor c: ", c.dtype)

Tensor c: 
 [[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]

Shape of tensor c:  (2, 2, 3)

Data type of tensor c:  float64


## Initialization functions

In [5]:
# All zeros
print("All zeros: \n", np.zeros((2,2)))

# All ones
print("\nAll ones: \n", np.ones((2,3,4)))

# All same value
print("\nAll same value: \n", np.full((2,2), 2))

# Identity matrix
print("\nIdentity matrix: \n", np.eye(3))

# Linspace
print("\nUniformly spaced elements: \n", np.linspace(start=0, stop=1, num=10, endpoint=False))

# Arange
print("\nNumpy array with range of numbers: \n", np.arange(start=0, stop=10, step=2, dtype=np.float64))

All zeros: 
 [[0. 0.]
 [0. 0.]]

All ones: 
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

All same value: 
 [[2 2]
 [2 2]]

Identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Uniformly spaced elements: 
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]

Numpy array with range of numbers: 
 [0. 2. 4. 6. 8.]


Numpy offers a variety of ways to generate "random" numbers.

In [6]:
# All random
# Setting a random seed is important for reproducibility of the code.
# It is good practice to use it in ML before moving to actual training as it makes debuging a lot easier.
np.random.seed(5)
print("\nRandom uniform: \n", np.random.random((2,2)))

# If high=None, then [0, low) is returned. By default, single integer is returned if size=None
print("\nRandom integer: \n", np.random.randint(low=2, high=9, size=(3, 3)))
print("\nRandom choice: \n", np.random.choice([1, 2, 3, 4, 5, 6], size=(4)))
print("\nSample from Binomial distribution: \n", np.random.binomial(n=10,p=0.5))


Random uniform: 
 [[0.22199317 0.87073231]
 [0.20671916 0.91861091]]

Random integer: 
 [[2 6 8]
 [5 2 8]
 [2 6 3]]

Random choice: 
 [6 1 4 5]

Sample from Binomial distribution: 
 4


## Array indexing
Indexing starts from 0. It is possible to use negative indexes (for example -1 for last element of array)

In [7]:
print("Array a: ", a)
print("First element of a: ", a[0])
print("Last element of a: ", a[2])
print("Last element of a: ", a[-1])

Array a:  [1 2 3]
First element of a:  1
Last element of a:  3
Last element of a:  3


Indexing in matrix and tensor is the same and we can index any column, row etc.

In [8]:
print("Matrix b: \n", b)
print("\nValue of b[0]: \n", b[0])
print("\nValue of b[-2]: \n", b[-2])
print("\nValue of b[0][1]: ", b[0][1])
print("Value of b[0, 1]: ", b[0, 1])
print("\nValue of b[0, :]: \n", b[0, :])
print("\nValue of b[0:2, 1:]: \n", b[0:2, 1:]) # General form is start:end

Matrix b: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Value of b[0]: 
 [1 2 3]

Value of b[-2]: 
 [4 5 6]

Value of b[0][1]:  2
Value of b[0, 1]:  2

Value of b[0, :]: 
 [1 2 3]

Value of b[0:2, 1:]: 
 [[2 3]
 [5 6]]


In [9]:
print("Tensor c: \n", c)
print("\nValue of c[0]: \n", c[0])
print("\nValue of c[-2]: \n", c[-2])
print("\nValue of c[0][1]: ", c[0][1])
print("Value of c[0][0][0]: ", c[0][0][0])
print("Value of c[0, 0, 0]: ", c[0, 0, 0])
print("\nValue of c[0, :, 0:2]: \n", c[0, :, 0:2])

Tensor c: 
 [[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]

Value of c[0]: 
 [[1. 2. 3.]
 [4. 5. 6.]]

Value of c[-2]: 
 [[1. 2. 3.]
 [4. 5. 6.]]

Value of c[0][1]:  [4. 5. 6.]
Value of c[0][0][0]:  1.0
Value of c[0, 0, 0]:  1.0

Value of c[0, :, 0:2]: 
 [[1. 2.]
 [4. 5.]]


## Basic operations

In [10]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

print("Matrix x: \n", x)
print("\nMatrix y: \n", y)

Matrix x: 
 [[1. 2.]
 [3. 4.]]

Matrix y: 
 [[5. 6.]
 [7. 8.]]


In [11]:
print("Addition:\n", x + y)
print("Subtraction:\n", y - x)
print("Elementwise multiplication:\n", x * y)
print("Multiplication:\n", np.matmul(x, y))
print("Multiplication x@y:\n", x@y)
print("Divison:\n", x / y)
print("x>2:\n", x>2)
print("Square root:\n", np.sqrt(x))
print("Exp:\n", np.exp(x))
print("Dot product:\n", np.dot(x[1], y[0]))
print("Transpose:\n", x.T)
print("Inverse:\n", np.linalg.inv(x))
print("Determinant:\n", np.linalg.det(y))

Addition:
 [[ 6.  8.]
 [10. 12.]]
Subtraction:
 [[4. 4.]
 [4. 4.]]
Elementwise multiplication:
 [[ 5. 12.]
 [21. 32.]]
Multiplication:
 [[19. 22.]
 [43. 50.]]
Multiplication x@y:
 [[19. 22.]
 [43. 50.]]
Divison:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
x>2:
 [[False False]
 [ True  True]]
Square root:
 [[1.         1.41421356]
 [1.73205081 2.        ]]
Exp:
 [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
Dot product:
 39.0
Transpose:
 [[1. 3.]
 [2. 4.]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant:
 -2.000000000000005


In [12]:
w = [0, 3, -2, 9, 5]
print("w:\n", w)
print("Argmax w:\n", np.argmax(w))
print("Max w:\n", np.max(w))

w:
 [0, 3, -2, 9, 5]
Argmax w:
 3
Max w:
 9


Boolean indexing

In [13]:
arr = np.array([0, -3, 4, -1, 2, 8, 5])
print("arr:\n", arr)
print("Boolean indexing:\n", arr[[False, False, True, False, False, True, True]])
print("arr>2:\n", arr>2)
print("arr[arr>2]:\n", arr[arr>2])
print("Remainder of division by 2:\n", np.remainder(c, 2)==0)
print("Even numbers:\n", c[np.remainder(c, 2)==0])

arr:
 [ 0 -3  4 -1  2  8  5]
Boolean indexing:
 [4 8 5]
arr>2:
 [False False  True False False  True  True]
arr[arr>2]:
 [4 8 5]
Remainder of division by 2:
 [[[False  True False]
  [ True False  True]]

 [[False  True False]
  [ True False  True]]]
Even numbers:
 [ 2.  4.  6.  8. 10. 12.]


## Practice problem: Solve system of equations
Solve the system of 5 equations involving 5 unknowns:
\begin{equation*}
x_1-7x_5 = 2
\end{equation*}
\begin{equation*}
x_2+9x_5=1
\end{equation*}
\begin{equation*}
x_3+x_5=3
\end{equation*}
\begin{equation*}
x_4-2x_5=5
\end{equation*}
\begin{equation*}
3x_1+2x_2-x_3+4x_5=9
\end{equation*}

In [15]:
x = np.zeros(5) # This is solution vector

A = np.eye(5)
A[:, 4] = np.array([-7, 9, 1, -2, 4])
A[4, :] = np.array([3, 2, -1, 0, 4])
b = np.array([2, 1, 3, 5, 9])

x = np.matmul(np.linalg.inv(A), b)

print(A)

print("Solution:\n")
print("x1=", x[0])
print("x2=", x[1])
print("x3=", x[2])
print("x4=", x[3])
print("x5=", x[4])

[[ 1.  0.  0.  0. -7.]
 [ 0.  1.  0.  0.  9.]
 [ 0.  0.  1.  0.  1.]
 [ 0.  0.  0.  1. -2.]
 [ 3.  2. -1.  0.  4.]]
Solution:

x1= 5.5
x2= -3.4999999999999982
x3= 2.5
x4= 6.0
x5= 0.4999999999999998


## Broadcasting
Broadcasting is one of the most important numpy features. The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is "broadcast" across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations.

In [ ]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
print("a * b, a as vector, b as vector:", a * b)

b = np.array([2])
print("a * b, a as vector, b as scalar:", a * b)

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([2,4,6])

print("Matrix a:\n", a)
print("Vector b:", b)
print("a + b, a as matrix, b as vector:\n", a + b)
print("a * b, a as matrix, b as vector:\n", a * b)
print("Dot product of a and b:\n", np.dot(a, b))

## Practice problem: Implement sigmoid function:
### Sigmoid function:

\begin{equation*}
S(x) = \frac{1}{1 + e^{-x}}
\end{equation*}

You can find more at *https://en.wikipedia.org/wiki/Sigmoid_function*

In [16]:
def sigmoid(x):
    S = 1 / (1 + np.exp(-x))
    return S

In [17]:
print("Sigmoid of \"0\":", sigmoid(0))
print("Expected value: 0.5")
testArray = np.array([1,5])
print("Sigmoid of [1,5]:", sigmoid(testArray))
print("Expected value: [0.73105858 0.99330715]")

Sigmoid of "0": 0.5
Expected value: 0.5
Sigmoid of [1,5]: [0.73105858 0.99330715]
Expected value: [0.73105858 0.99330715]
